sudo: false

language: go

go:
  - 1.5.1
  - 1.5
  - 1.4.1
  - 1.4

before_install:
  - apt-get update -qq
  - apt-get install -y zookeeper-server
  - service zookeeper-server init
  - service zookeeper-server start