sudo: true

language: go

go:
  - 1.5.1
  - 1.5
  - 1.4.1
  - 1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y zookeeper-server
  - sudo service zookeeper-server init
  - sudo service zookeeper-server start