sudo: false

language: go

go:
  - 1.5.1
  - 1.5
  - 1.4.1
  - 1.4

before_install:
  - ZK_VERSION=3.4.7
  - wget http://apache.claz.org/zookeeper/zookeeper-${ZK_VERSION}/zookeeper-${ZK_VERSION}.tar.gz
  - tar -zxvf zookeeper*tar.gz
  - cd zookeeper-${ZK_VERSION}
  - DATADIR="${PWD}/datadir"
  - mkdir -p ${DATADIR}
  - mkdir -p conf
  - touch conf/zoo.cfg
  - echo "tickTime=2000" >> conf/zoo.cfg
  - echo "clientPort=2181" >> conf/zoo.cfg
  - echo "dataDir=${DATADIR}" >> conf/zoo.cfg
  - bin/zkServer.sh start &